# Generated by Django 5.0.6 on 2024-06-14 15:30

import django.contrib.admin.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('biblio_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunter',
            name='adherant',
        ),
        migrations.AlterField(
            model_name='gerer',
            name='ida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rechercher',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rechercher',
            name='idv',
        ),
        migrations.RemoveField(
            model_name='rechercher',
            name='isbn',
        ),
        migrations.CreateModel(
            name='CustomLogEntry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='exemplaire',
            name='emprunte',
        ),
        migrations.AddField(
            model_name='emprunter',
            name='bibliothecaire_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprunter_bibliothecaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emprunter',
            name='date_rendu',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprunter',
            name='num_extensions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emprunter',
            name='rendu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='empruntable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='banni',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_emprunt',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprunter',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprunter_utilisateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personne',
            name='role',
            field=models.CharField(choices=[('UTILISATEUR', 'Utilisateur'), ('BIBLIOTHECAIRE', 'Bibliothecaire'), ('ADMINSUP', 'AdminSup')], default='UTILISATEUR', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Consulter',
            fields=[
                ('id_consultation', models.AutoField(primary_key=True, serialize=False)),
                ('date_sortie', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('rendu', models.BooleanField(default=False)),
                ('bibliothecaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulter_bibliothecaire', to=settings.AUTH_USER_MODEL)),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.exemplaire')),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.ouvrage')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulter_utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Adherent',
        ),
        migrations.DeleteModel(
            name='Visiteur',
        ),
        migrations.DeleteModel(
            name='Rechercher',
        ),
    ]
