# Generated by Django 5.0.6 on 2024-06-14 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0002_remove_emprunter_adherant_alter_gerer_ida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.exemplaire')),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_app.ouvrage')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
