# Generated by Django 5.0.6 on 2024-07-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0004_personne_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunter',
            name='date_sortie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_emprunt',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateField(),
        ),
    ]
